--DML

--INSERIR DADOS
insert into ALUNO(RA,NOME,DATA_MATRICULA,DATA_NASC)
values (00001,'GUILHERME',DATE '2026-01-01',DATE '2001-08-14');

-- ALTERAR DADO
UPDATE ALUNO
SET NOME = 'GUILHERME FERREIRA'
WHERE RA = 00001; 

--DELETAR
DELETE FROM ALUNO
WHERE RA=0001;

DESCRIBE ALUNO;

select * from ALUNO;
