--DQL 
--CONSULTAS COM USO DO BD EMP and DEPT (SCOOT) DO ORACLE

SELECT * FROM SCOTT.EMP; --SELECIONAR TODOS OS CAMPOS DE UMA TABELA

SELECT ENAME FROM SCOTT.EMP; --SELECIONA SOMENTE OS CAMPOS DE NOME DA TABELA 

SELECT ENAME NOME, SAL "SALARIO DO FUNC", JOB AS "CARGO DO FUNC"
FROM SCOTT.EMP; --DADO APILIDOS AS COLUNAS PARA FACILITAR A COMPREENSAO 

SELECT ENAME, SAL, SAL*12 "SALARIO ANUAL"
FROM SCOTT.EMP --GERANDO UMA CONSULTA A TABELA COM NOVOS DADOS 
--USANDO OS PROPRIOS DADOS DA TABELA CONSULTAMOS E EXIBIMOS NOVAS INFORMAÇÕES 
-- APARTIR DELA

SELECT ENAME, SAL, SAL*0.1 "ADICIONAL DE 10%", SAL+(SAL*0.1)"SALARIO COM ALEMENTO APLICADO"
FROM SCOTT.EMP -- SIMULANDO ALMENTO DE SALARIO DE 10%

SELECT ENAME , JOB , ENAME || ' TEM O CARGO DE ' || JOB "NOME É CARGO"
FROM SCOTT.EMP; -- CONTATENAÇÃO DE DADOS 

SELECT DISTINCT JOB
FROM SCOTT.EMP; -- EXIBIR CARGOS DA EMPRESA SEM REPETIÇÃO DE NOMES

SELECT ENAME,JOB,DEPTNO
FROM SCOTT.EMP
WHERE JOB = 'CLERK'; -- EXIBIR SOMENTE QUEM TRABALHA COM CLERK

SELECT ENAME, SAL
FROM SCOTT.EMP
WHERE SAL BETWEEN 1000 AND 1500; -- CONSULTA A TABELA E EXIBE TODOS FUNCIONARIOS COM SALARIO ENTRE 1000 A 1500

SELECT EMPNO, ENAME, SAL, MGR
FROM SCOTT.EMP
WHERE MGR IN (7902,7566,7788); -- EXIBE DADOS DE FUNCIONARIOS QUE TEM O MGR DEFINIDO PELO IN

SELECT ENAME
FROM SCOTT.EMP
WHERE ENAME LIKE 'S%'; -- EXIBE FUNCIONARIOS QUE COMEÇÃO COM A LETRA S (POSSIBILITADO PELO %)

SELECT ENAME
FROM SCOTT.EMP
WHERE ENAME LIKE 'S_';  -- EXIBE FUNCIONARIOS QUE TEM A LETRA S NO NOME

SELECT ENAME,MGR
FROM SCOTT.EMP
WHERE MGR IS NULL; -- EXIBE TODOS OS FUNCIONARIOS QUE TEM O MGR SEM NENHUM VALOR SALVO

SELECT EMPNO, ENAME, JOB, SAL
FROM SCOTT.EMP
WHERE SAL>= 1100
AND JOB = 'CHERK'; -- EXIBIR DADOS DOS FUNCIONARIOS ONDE O VALOR DO SALARIO É IGUAL OU SUPERIOR A 1100 E QUE O CARGO SEJA CHERK

SELECT EMPNO, ENAME, JOB, SAL
FROM SCOTT.EMP
WHERE SAL>= 1100
OR JOB = 'CHERK';-- EXIBIR DADOS DOS FUNCIONARIOS ONDE O VALOR DO SALARIO É IGUAL OU SUPERIOR A 1100 OU QUE O CARGO SEJA CHERK

SELECT ENAME, JOB
FROM SCOTT.EMP
WHERE JOB NOT IN ('CHERK','MANAGER','ANALYST') -- NÃO EXIBIR FUNCIONARIOS COM CARGOS DISCRITOS EM ()

SELECT ENAME, JOB, DEPTNO, HIREDATE
FROM SCOTT.EMP
ORDER BY HIREDATE ASC; -- ORDENAR TABELA PELAS DATAS(QUANDO NÃO É DEFINIDO ISSO A TABELA EXIBE OS DADOS POR ORDEM DE CADASTRO)
--ASC EM ORDEM CRESCENTE 
-- DESC EM ORDEM DECRESCENTE

SELECT EMPNO, ENAME, DEPTNO
FROM SCOTT.EMP
WHERE ENAME = UPPER('blake');
-- devido a tabela ter nomes salvos em caixa alta ao consultalo em a palavra reservada 
--UPPER não sera possivel encontrar o mesmo.
--LOWER para minúsculas , UPPER para maiúsculas, INITCAP para primeira letra maiúscula e restante minúsculas.

SELECT ENAME,ROUND((SYSDATE-HIREDATE)/7,2) WEEKS
FROM SCOTT.EMP
WHERE DEPTNO = 10; -- SYSDATE = DATA ATUAL- DATA DE ADIMIÇÃO DIVIDIDO POR 7
-- COM ESSE CALCULO DESCOBRIMOS A QUANTAS SEMANAS OS FUNCIONARIOS
--DO DEPARTAMENTO 10 ESTÃO NA EMPRESA

SELECT TO_CHAR(SAL,'$99,999')SALARY
FROM SCOTT.EMP
WHERE ENAME = 'SCOTT'; -- FORMATAÇÃO DE SALARIO TO_CHAR()= CONVERTE DADOS PARA STRINGS

SELECT TO_CHAR(SYSDATE,'DAY/YEAR') FROM DUAL;--FORMATAÇÃO DE DATA

SELECT ENAME, SAL, TO_CHAR(SAL, 'L999,999,999.99') FROM SCOTT.EMP
-- FORMATAÇÃO DE SALARIO TO_CHAR()= CONVERTE DADOS PARA STRINGS
  
SELECT JOB, SAL,
    DECODE(JOB,'ANALYST', SAL*1.1,
        'CLERK',SAL*1.15,
        'MANAGER', SAL*1.20,
        SAL)
        REVISED_SALARY
FROM SCOTT.EMP;
-- REVISÃO DE SALARI. ALTERAÇÃO DE SALARIOS EM PORCENTAGEM X PARA CADA CARGO
-- DECODE = FUNÇÃO SEMELHANTE AO IF AND ELSE)

SELECT ENAME, JOB, SAL,(
    CASE
        WHEN JOB = 'CLERK'
        THEN SAL*2 ELSE SAL*1.5 END) "AUMENTO SALARIAL"
FROM SCOTT.EMP; 
--CONSULTA QUE GERA ALMENTO DE SALARIO PARA CLERK DOBRADO E PARA
-- OS DEMAIS CARGOS DE 50%.
-- CASE É SEMELHANTE AO DECODE SÓ QUE MAIS FACIL COMPREENÇÃO
