--DQL    
--CONSULTAS COM USO DO BD EMP and DEPT (SCOOT) DO ORACLE

SELECT * FROM SCOTT.EMP; --SELECIONAR TODOS OS CAMPOS DE UMA TABELA

SELECT ENAME FROM SCOTT.EMP; --SELECIONA SOMENTE OS CAMPOS DE NOME DA TABELA 

SELECT ENAME NOME, SAL "SALARIO DO FUNC", JOB AS "CARGO DO FUNC"
FROM SCOTT.EMP; --DADO APILIDOS AS COLUNAS PARA FACILITAR A COMPREENSAO 

SELECT ENAME, SAL, SAL*12 "SALARIO ANUAL"
FROM SCOTT.EMP --GERANDO UMA CONSULTA A TABELA COM NOVOS DADOS 
--USANDO OS PROPRIOS DADOS DA TABELA CONSULTAMOS E EXIBIMOS NOVAS INFORMAÇÕES 
-- APARTIR DELA

SELECT ENAME, SAL, SAL*0.1 "ADICIONAL DE 10%", SAL+(SAL*0.1)"SALARIO COM ALEMENTO APLICADO"
FROM SCOTT.EMP -- SIMULANDO ALMENTO DE SALARIO DE 10%

SELECT ENAME , JOB , ENAME || ' TEM O CARGO DE ' || JOB "NOME É CARGO"
FROM SCOTT.EMP; -- CONTATENAÇÃO DE DADOS 

SELECT DISTINCT JOB
FROM SCOTT.EMP; -- EXIBIR CARGOS DA EMPRESA SEM REPETIÇÃO DE NOMES

SELECT ENAME,JOB,DEPTNO
FROM SCOTT.EMP
WHERE JOB = 'CLERK'; -- EXIBIR SOMENTE QUEM TRABALHA COM CLERK

SELECT ENAME, SAL
FROM SCOTT.EMP
WHERE SAL BETWEEN 1000 AND 1500; -- CONSULTA A TABELA E EXIBE TODOS FUNCIONARIOS COM SALARIO ENTRE 1000 A 1500

SELECT EMPNO, ENAME, SAL, MGR
FROM SCOTT.EMP
WHERE MGR IN (7902,7566,7788); -- EXIBE DADOS DE FUNCIONARIOS QUE TEM O MGR DEFINIDO PELO IN

SELECT ENAME
FROM SCOTT.EMP
WHERE ENAME LIKE 'S%'; -- EXIBE FUNCIONARIOS QUE COMEÇÃO COM A LETRA S (POSSIBILITADO PELO %)

SELECT ENAME
FROM SCOTT.EMP
WHERE ENAME LIKE 'S_';  -- EXIBE FUNCIONARIOS QUE TEM A LETRA S NO NOME

SELECT ENAME,MGR
FROM SCOTT.EMP
WHERE MGR IS NULL; -- EXIBE TODOS OS FUNCIONARIOS QUE TEM O MGR SEM NENHUM VALOR SALVO

SELECT EMPNO, ENAME, JOB, SAL
FROM SCOTT.EMP
WHERE SAL>= 1100
AND JOB = 'CHERK'; -- EXIBIR DADOS DOS FUNCIONARIOS ONDE O VALOR DO SALARIO É IGUAL OU SUPERIOR A 1100 E QUE O CARGO SEJA CHERK

SELECT EMPNO, ENAME, JOB, SAL
FROM SCOTT.EMP
WHERE SAL>= 1100
OR JOB = 'CHERK';-- EXIBIR DADOS DOS FUNCIONARIOS ONDE O VALOR DO SALARIO É IGUAL OU SUPERIOR A 1100 OU QUE O CARGO SEJA CHERK

SELECT ENAME, JOB
FROM SCOTT.EMP
WHERE JOB NOT IN ('CHERK','MANAGER','ANALYST') -- NÃO EXIBIR FUNCIONARIOS COM CARGOS DISCRITOS EM ()

SELECT ENAME, JOB, DEPTNO, HIREDATE
FROM SCOTT.EMP
ORDER BY HIREDATE ASC; -- ORDENAR TABELA PELAS DATAS(QUANDO NÃO É DEFINIDO ISSO A TABELA EXIBE OS DADOS POR ORDEM DE CADASTRO)
--ASC EM ORDEM CRESCENTE 
-- DESC EM ORDEM DECRESCENTE

SELECT EMPNO, ENAME, DEPTNO
FROM SCOTT.EMP
WHERE ENAME = UPPER('blake');
-- devido a tabela ter nomes salvos em caixa alta ao consultalo em a palavra reservada 
--UPPER não sera possivel encontrar o mesmo.
--LOWER para minúsculas , UPPER para maiúsculas, INITCAP para primeira letra maiúscula e restante minúsculas.

SELECT ENAME,ROUND((SYSDATE-HIREDATE)/7,2) WEEKS
FROM SCOTT.EMP
WHERE DEPTNO = 10; -- SYSDATE = DATA ATUAL- DATA DE ADIMIÇÃO DIVIDIDO POR 7
-- COM ESSE CALCULO DESCOBRIMOS A QUANTAS SEMANAS OS FUNCIONARIOS
--DO DEPARTAMENTO 10 ESTÃO NA EMPRESA

SELECT TO_CHAR(SAL,'$99,999')SALARY
FROM SCOTT.EMP
WHERE ENAME = 'SCOTT'; -- FORMATAÇÃO DE SALARIO TO_CHAR()= CONVERTE DADOS PARA STRINGS

SELECT TO_CHAR(SYSDATE,'DAY/YEAR') FROM DUAL;--FORMATAÇÃO DE DATA

SELECT ENAME, SAL, TO_CHAR(SAL, 'L999,999,999.99') FROM SCOTT.EMP
-- FORMATAÇÃO DE SALARIO TO_CHAR()= CONVERTE DADOS PARA STRINGS
  
SELECT JOB, SAL,
    DECODE(JOB,'ANALYST', SAL*1.1,
        'CLERK',SAL*1.15,
        'MANAGER', SAL*1.20,
        SAL)
        REVISED_SALARY
FROM SCOTT.EMP;
-- REVISÃO DE SALARI. ALTERAÇÃO DE SALARIOS EM PORCENTAGEM X PARA CADA CARGO
-- DECODE = FUNÇÃO SEMELHANTE AO IF AND ELSE)

SELECT ENAME, JOB, SAL,(
    CASE
        WHEN JOB = 'CLERK'
        THEN SAL*2 ELSE SAL*1.5 END) "AUMENTO SALARIAL"
FROM SCOTT.EMP; 
--CONSULTA QUE GERA ALMENTO DE SALARIO PARA CLERK DOBRADO E PARA
-- OS DEMAIS CARGOS DE 50%.
-- CASE É SEMELHANTE AO DECODE SÓ QUE MAIS FACIL COMPREENÇÃO

SELECT SCOTT.EMP.EMPNO, SCOTT.EMP.ENAME, SCOTT.EMP.DEPTNO, SCOTT.DEPT.DEPTNO, SCOTT.DEPT.LOC
FROM SCOTT.EMP JOIN SCOTT.DEPT
ON SCOTT.EMP.DEPTNO = SCOTT.DEPT.DEPTNO;-- MESCLA INFORMAÇÕES DE AMBAS AS 
--TABELAS ONDE ESTIVER O MESMO CODIGO DE DEPARTAMENTO

SELECT E.EMPNO, E.ENAME, E.DEPTNO, D.DEPTNO, D.LOC
FROM SCOTT.EMP E JOIN SCOTT.DEPT D
ON (E.DEPTNO=D.DEPTNO);-- MESMO CODIGO DO DESCRITO ACIMA, MAS COM USO DE 
--APELIDOS PARA AS TABELAS

SELECT E.LAST_NAME "PRIMEIRO NOME", D.DEPARTMENT_NAME "DEPARTAMENTO", L.CITY "CIDADE"
FROM HR.EMPLOYEES E JOIN HR.DEPARTMENTS D
ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID)
JOIN HR.LOCATIONS L 
ON(D.LOCATION_ID = L.LOCATION_ID);-- NO BD HR DO ORACLE USADO PARA FAZER UM JOIN
-- TRIDIMENCIONAL JUNTANDO INFORMAÇÕES DE 3 TABELAS DISTINTAS

SELECT E.LAST_NAME, D.DEPARTMENT_ID, D.DEPARTMENT_NAME
FROM HR.EMPLOYEES E LEFT OUTER JOIN HR.DEPARTMENTS D
ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID)
  ORDER BY E.LAST_NAME; --JOIN EXTERNA

SELECT FUNCIONARIO.ENAME || 'TRABALHA PARA'  || GERENTE.ENAME "FUNCIONARIOS E GERENTES"
FROM SCOTT.EMP FUNCIONARIO JOIN SCOTT.EMP GERENTE
ON (FUNCIONARIO.MGR = GERENTE.EMPNO) -- AUTER JOIN(A JUNÇÃO DA TABELA COM ELA MESMA) 

SELECT DEPTNO,COUNT(DEPTNO) "QUANTIDADE DE FUNCIONARIOS", JOB, SUM(SAL) "SOMA DOS SALARIOS"
FROM SCOTT.EMP
GROUP BY DEPTNO,JOB
ORDER BY DEPTNO,JOB;-- AGRUPA POR DEPARTAMENTO E CARGO E CALCULA A SOMA DOS SALARIOS DE CADA CARGO EM CADA DEPARTAMENTO

SELECT DEPTNO, SUM(SAL)
FROM SCOTT.EMP
GROUP BY DEPTNO
HAVING SUM(SAL)>9000;-- AGRUPA O SALARIOS DOS DEPARTAMENTOS E SOMA OS SEUS VALORES DANDO
-- GASTO TOTAL COM CADA DEPARTAMENTO, O HAVING FILTRA E EXIBE SOMENTE OS DEPARTAMENTOS
-- QUE TEM GASTO COM FUNCIONARIOS ACIMA DE 9000

SELECT ENAME
FROM SCOTT.EMP 
WHERE SAL>
    (SELECT SAL
    FROM SCOTT.EMP
    WHERE EMPNO=7566); -- SUBCONSULTA = EXIBE OS NOMES DOS FUNCIONARIOS QUE RECEBEM MAIS
    -- QUE O FUNCIONARIO 7566

SELECT EMPNO, ENAME, JOB
FROM SCOTT.EMP
    WHERE SAL < ANY 
        (SELECT SAL
        FROM SCOTT.EMP
        WHERE JOB = 'CLERK')
    AND JOB<> 'CLERK'; -- ESTA CONSULTA RETORNA TODOS SALARIOS DO CARGO CLERK POR SER VARIOS
    -- VALORES DENOMINAMOS ESTE TIPO DE CODIGO COM SUBCONSULTAS DE VARIAS LINHAS E COLUNAS
    -- POR ESTE MOTIVO USAMOS A PALAVRA RESERVADA ANY QUE PODE EXIBIR:
    -- SALARIOS MAIORES QUE: 800 OU 1300 OU 1100 OU 950

SELECT EMPNO, ENAME, JOB
FROM SCOTT.EMP
    WHERE SAL < ALL 
        (SELECT AVG(SAL)
        FROM SCOTT.EMP
        GROUP BY DEPTNO); -- ESTA CONSULTA RETORNA TODOS SALARIOS (ALL) MAIORES QUE A MEDIA DE CADA DEPARTAMENTO
        
CREATE OR REPLACE VIEW DEPT10_VU
AS SELECT ENAME,SAL,DEPTNO
FROM SCOTT.EMP
WHERE DEPTNO=10; --CRIAÇÃO DE VIEW SIMPLES

CREATE VIEW DEPT_SUM_VU
(NAME,MINSAL,MAXSAL,AVGSAL)--APELIDOS DAS COLUNAS DA VIEW
AS SELECT D.DNAME,MIN(E.SAL),MAX(E.SAL),AVG(E.SAL)
FROM SCOTT.EMP E JOIN SCOTT.DEPT D
ON (E.DEPTNO = D.DEPTNO)
GROUP BY D.DNAME; -- VIEW COMPLEXA. COMPLEXA POR TER FUNÇÕES DE GRUPO 

CREATE OR RAPLACE VIEW EMPVU20
AS SELECT * 
FROM SCOTT.EMP
WHERE DEPTNO = 20
WITH CHECK OPTION CONTRAINT EMPVU20_CK; --IMPEDE QUE ALTERA A CONDIÇÃO WHERE DESSA VIEW


