--DQL 

SELECT * FROM SCOTT.EMP; --SELECIONAR TODOS OS CAMPOS DE UMA TABELA

SELECT ENAME FROM SCOTT.EMP; --SELECIONA SOMENTE OS CAMPOS DE NOME DA TABELA 

SELECT ENAME NOME, SAL "SALARIO DO FUNC", JOB AS "CARGO DO FUNC"
FROM SCOTT.EMP; --DADO APILIDOS AS COLUNAS PARA FACILITAR A COMPREENSAO 

SELECT ENAME, SAL, SAL*12 "SALARIO ANUAL"
FROM SCOTT.EMP --GERANDO UMA CONSULTA A TABELA COM NOVOS DADOS 
--USANDO OS PROPRIOS DADOS DA TABELA CONSULTAMOS E EXIBIMOS NOVAS INFORMAÇÕES 
-- APARTIR DELA

SELECT ENAME, SAL, SAL*0.1 "ADICIONAL DE 10%", SAL+(SAL*0.1)"SALARIO COM ALEMENTO APLICADO"
FROM SCOTT.EMP -- SIMULANDO ALMENTO DE SALARIO DE 10%

SELECT ENAME , JOB , ENAME || ' TEM O CARGO DE ' || JOB "NOME É CARGO"
FROM SCOTT.EMP; -- CONTATENAÇÃO DE DADOS 

SELECT DISTINCT JOB

FROM SCOTT.EMP; -- EXIBIR CARGOS DA EMPRESA SEM REPETIÇÃO DE NOMES

SELECT ENAME,JOB,DEPTNO
FROM SCOTT.EMP
WHERE JOB = 'CLERK'; -- EXIBIR SOMENTE QUEM TRABALHA COM CLERK
